# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fastaiOnCampus',
                'doc_host': 'https://fabraz.github.io',
                'git_url': 'https://github.com/fabraz/fastaiOnCampus',
                'lib_path': 'fastaiOnCampus'},
  'syms': {'fastaiOnCampus.core': {'fastaiOnCampus.core.foo': ('core.html#foo', 'fastaiOnCampus/core.py')}}}